using System.Collections.Generic;

namespace TesvikProgrami
{
    public static class BildirgeOlusturmaSabitleri
    {

        public const int IlkSigortaliSayi = 101;

        public const int DevamSayfasiIlkSigortaliSayi = 64;

        public const int IlkSigortaliArtis = 5;

        public static Dictionary<Enums.BildirgeHucreleri, string> ExcelHucreleri = new Dictionary<Enums.BildirgeHucreleri, string>
        {
            { Enums.BildirgeHucreleri.IsyeriSicil1, "BQ13"},
            { Enums.BildirgeHucreleri.IsyeriSicil2, "BU13"},
            { Enums.BildirgeHucreleri.IsyeriSicil3, "BY13"},
            { Enums.BildirgeHucreleri.IsyeriSicil4, "CC13"},
            { Enums.BildirgeHucreleri.IsyeriSicil5, "CG13"},
            { Enums.BildirgeHucreleri.IsyeriSicil6, "CK13"},
            { Enums.BildirgeHucreleri.IsyeriSicil7, "CO13"},
            { Enums.BildirgeHucreleri.IsyeriSicil8, "CS13"},
            { Enums.BildirgeHucreleri.IsyeriSicil9, "CW13"},
            { Enums.BildirgeHucreleri.IsyeriSicil10, "DA13"},
            { Enums.BildirgeHucreleri.IsyeriSicil11, "DE13"},
            { Enums.BildirgeHucreleri.IsyeriSicil12, "DI13"},
            { Enums.BildirgeHucreleri.IsyeriSicil13, "DM13"},
            { Enums.BildirgeHucreleri.IsyeriSicil14, "DQ13"},
            { Enums.BildirgeHucreleri.IsyeriSicil15, "DU13"},
            { Enums.BildirgeHucreleri.IsyeriSicil16, "DY13"},
            { Enums.BildirgeHucreleri.IsyeriSicil17, "EC13"},
            { Enums.BildirgeHucreleri.IsyeriSicil18, "EG13"},
            { Enums.BildirgeHucreleri.IsyeriSicil19, "EK13"},
            { Enums.BildirgeHucreleri.IsyeriSicil20, "EO13"},
            { Enums.BildirgeHucreleri.IsyeriSicil21, "ES13"},
            { Enums.BildirgeHucreleri.IsyeriSicil22, "EW13"},
            { Enums.BildirgeHucreleri.IsyeriSicil23, "FA13"},
            { Enums.BildirgeHucreleri.IsyeriSicil24, "FE13"},
            { Enums.BildirgeHucreleri.IsyeriSicil25, "FI13"},
            { Enums.BildirgeHucreleri.IsyeriSicil26, "FM13"},
            { Enums.BildirgeHucreleri.BelgeYil, "HE8"},
            { Enums.BildirgeHucreleri.BelgeAy, "HE12"},
            { Enums.BildirgeHucreleri.Asil, "HE18"},
            { Enums.BildirgeHucreleri.Ek, "HU18"},
            { Enums.BildirgeHucreleri.Iptal, "IK18"},
            { Enums.BildirgeHucreleri.BildirgeBelgeTuru, "HE27"},
            { Enums.BildirgeHucreleri.BildirgeKanun, "HE32"},
            { Enums.BildirgeHucreleri.ToplamSayfaSayisi, "HE40"},
            { Enums.BildirgeHucreleri.SayfaNo, "HE46"},
            { Enums.BildirgeHucreleri.Isveren, "BZ19"},
            { Enums.BildirgeHucreleri.IsverenAdiSoyadi, "AW23"},
            { Enums.BildirgeHucreleri.IsverenUnvan, "AW26"},
            { Enums.BildirgeHucreleri.IsverenAdres, "AW29"},
            { Enums.BildirgeHucreleri.IsverenSemt, "AW34"},
            { Enums.BildirgeHucreleri.IsverenIlce, "BT34"},
            { Enums.BildirgeHucreleri.IsverenIl, "BT37"},
            { Enums.BildirgeHucreleri.IsverenDisKapiNo, "AW37"},
            { Enums.BildirgeHucreleri.IsverenIcKapiNo, "AW40"},
            { Enums.BildirgeHucreleri.IsverenPostaKodu, "BT40"},
            { Enums.BildirgeHucreleri.IsverenTelefon, "AW43"},
            { Enums.BildirgeHucreleri.IsverenEposta, "BT43"},
            { Enums.BildirgeHucreleri.IsverenTckimlikNo, "AW47"},
            { Enums.BildirgeHucreleri.SigortaliyiDevirAlan, "FM19"},
            { Enums.BildirgeHucreleri.AltIsveren, "DP19"},
            { Enums.BildirgeHucreleri.AltIsverenAdiSoyadi, "CP23"},
            { Enums.BildirgeHucreleri.AltIsverenUnvan, "CP26"},
            { Enums.BildirgeHucreleri.AltIsverenAdres, "CP29"},
            { Enums.BildirgeHucreleri.AltIsverenSemt, "CP34"},
            { Enums.BildirgeHucreleri.AltIsverenIlce, "EF34"},
            { Enums.BildirgeHucreleri.AltIsverenIl, "EF37"},
            { Enums.BildirgeHucreleri.AltIsverenDisKapiNo, "CP37"},
            { Enums.BildirgeHucreleri.AltIsverenIcKapiNo, "CP40"},
            { Enums.BildirgeHucreleri.AltIsverenPostaKodu, "EF40"},
            { Enums.BildirgeHucreleri.AltIsverenTelefon, "CP43"},
            { Enums.BildirgeHucreleri.AltIsverenEposta, "EF43"},
            { Enums.BildirgeHucreleri.AltIsverenTckimlikNo, "CP47"},
            { Enums.BildirgeHucreleri.SigortaliSayisi, "AX61"},
            { Enums.BildirgeHucreleri.PrimOdemeGunSayisi, "AX65"},
            { Enums.BildirgeHucreleri.AyIcindeIseGirenler, "AX69"},
            { Enums.BildirgeHucreleri.AyIcindeIstenCikanlar, "AX73"},
            { Enums.BildirgeHucreleri.KisaVadeliSigortaKollariPrimiToplamKazanc, "EM65"},
            { Enums.BildirgeHucreleri.MalullukYaslilikSigortasiToplamKazanc, "EM69"},
            { Enums.BildirgeHucreleri.GenelSaglikSigortasiPrimiToplamKazanc, "EM73"},
            { Enums.BildirgeHucreleri.SosyalGuvenlikDestekPrimiToplamKazanc, "EM77"},
            { Enums.BildirgeHucreleri.IssizlikSigortasiPrimiToplamKazanc, "EM81"},
            { Enums.BildirgeHucreleri.GenelToplamKazanc, "EM85"},
            { Enums.BildirgeHucreleri.KisaVadeliSigortaKollariPrimiOrani, "GN65"},
            { Enums.BildirgeHucreleri.MalullukYaslilikSigortasiPrimOrani, "GN69"},
            { Enums.BildirgeHucreleri.GenelSaglikSigortasiPrimOrani, "GN73"},
            { Enums.BildirgeHucreleri.SosyalGuvenlikDestekPrimOrani, "GN77"},
            { Enums.BildirgeHucreleri.IssizlikSigortasiPrimOrani, "GN81"},
            { Enums.BildirgeHucreleri.GenelToplamPrimOrani, "GN85"},
            { Enums.BildirgeHucreleri.KisaVadeliSigortaKollariPrimTutari, "HL65"},
            { Enums.BildirgeHucreleri.MalullukYaslilikSigortasiPrimTutari, "HL69"},
            { Enums.BildirgeHucreleri.GenelSaglikSigortasiPrimTutari, "HL73"},
            { Enums.BildirgeHucreleri.SosyalGuvenlikDestekPrimTutari, "HL77"},
            { Enums.BildirgeHucreleri.IssizlikSigortasiPrimTutari, "HL81"},
            { Enums.BildirgeHucreleri.GenelToplamPrimTutari, "HL85"},
            { Enums.BildirgeHucreleri.SigortaliSosyalGuvenlikSicilNo, "I"},
            { Enums.BildirgeHucreleri.SigortaliAdi, "AP"},
            { Enums.BildirgeHucreleri.SigortaliSoyadi, "BN"},
            { Enums.BildirgeHucreleri.SigortaliIlkSoyadi, "CL"},
            { Enums.BildirgeHucreleri.SigortaliPrimOdemeGunu, "DC"},
            { Enums.BildirgeHucreleri.SigortaliUcret, "DJ"},
            { Enums.BildirgeHucreleri.SigortaliIkramiye, "EM"},
            { Enums.BildirgeHucreleri.SigortaliIseGirisTarihiGun, "FQ"},
            { Enums.BildirgeHucreleri.SigortaliIseGirisTarihiAy, "GB"},
            { Enums.BildirgeHucreleri.SigortaliIstenCikisTarihiGun, "GM"},
            { Enums.BildirgeHucreleri.SigortaliIstenCikisTarihiAy, "GX"},
            { Enums.BildirgeHucreleri.SigortaliEksikGunSayisi, "HI"},
            { Enums.BildirgeHucreleri.SigortaliEksikGunNedeni, "HQ"},
            { Enums.BildirgeHucreleri.SigortaliIstenCikisNedeni, "HZ"},
            { Enums.BildirgeHucreleri.IlkSayfaToplamSigortaliSayisi, "BZ141"},
            { Enums.BildirgeHucreleri.IlkSayfaToplamPrimeEsasKazanc, "DJ141"},
            { Enums.BildirgeHucreleri.IlkSayfaToplamPrimOdemeGunu, "CR141"},
            { Enums.BildirgeHucreleri.DevamBuSayfaToplamPrimeEsasKazanc, "DJ195"},
            { Enums.BildirgeHucreleri.DevamBuSayfaToplamPrimOdemeGunu, "CR195"},
            { Enums.BildirgeHucreleri.DevamBuSayfaToplamSigortaliSayisi, "BZ195"},
            { Enums.BildirgeHucreleri.DevamOncekiSayfaToplamPrimeEsasKazanc, "DJ199"},
            { Enums.BildirgeHucreleri.DevamOncekiSayfaToplamPrimOdemeGunu, "CR199"},
            { Enums.BildirgeHucreleri.DevamOncekiSayfaToplamSigortaliSayisi, "BZ199"},
            { Enums.BildirgeHucreleri.DevamTumSayfalarToplamPrimeEsasKazanc, "DJ203"},
            { Enums.BildirgeHucreleri.DevamTumSayfalarToplamPrimOdemeGunu, "CR203"},
            { Enums.BildirgeHucreleri.DevamTumSayfalarToplamSigortaliSayisi, "BZ203"},
            { Enums.BildirgeHucreleri.IlkSayfaAciklama, "C146"},
            { Enums.BildirgeHucreleri.DevamSayfaAciklama, "C211"},
            { Enums.BildirgeHucreleri.IlkSayfaBilgiler, "IV1"}
        };
       
    }

}
