//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesvikProgrami
{

    public partial class AsgariUcretler
    {
        public long ID { get; set; }
        public string Baslangic { get; set; }
        public string Bitis { get; set; }
        public double AsgariUcretTutari { get; set; }
    }
}
