//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesvikProgrami
{
    using System;
    using System.Collections.Generic;
    
    public partial class BelgeTurleri
    {
        public long BelgeTuruID { get; set; }
        public double MalulYaslilikOraniSigortali { get; set; }
        public double MalulYaslilikOraniIsveren { get; set; }
        public double GenelSaglikSigortali { get; set; }
        public double GenelSaglikIsveren { get; set; }
        public double SosyalDestekSigortali { get; set; }
        public double SosyalDestekIsveren { get; set; }
        public double IssizlikSigortali { get; set; }
        public double IssizlikIsveren { get; set; }
    }
}
