//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesvikProgrami
{

    public partial class Cari14857YapilanSirketler
    {
        public long Id { get; set; }
        public long SirketId { get; set; }
    
        public virtual Sirketler Sirketler { get; set; }
    }
}
