//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesvikProgrami
{

    public partial class DonusturulecekKanunlar
    {
        public long ID { get; set; }
        public string TesvikKanunNo { get; set; }
        public string DonusturulenKanunNo { get; set; }
        public decimal SadeceCari { get; set; }
    }
}
