//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesvikProgrami
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isyerleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Isyerleri()
        {
            this.AsgariUcretDestekTutarlari = new HashSet<AsgariUcretDestekTutarlari>();
            this.BasvuruDonemleri = new HashSet<BasvuruDonemleri>();
            this.BorcluAylar = new HashSet<BorcluAylar>();
            this.AylikCalisanSayilari = new HashSet<AylikCalisanSayilari>();
        }
    
        public long IsyeriID { get; set; }
        public long SirketID { get; set; }
        public string SubeAdi { get; set; }
        public string IsyeriSicilNo { get; set; }
        public string TaseronNo { get; set; }
        public string SosyalGuvenlikKurumu { get; set; }
        public decimal Aktif { get; set; }
        public string KullaniciAdi { get; set; }
        public string KullaniciKod { get; set; }
        public string SistemSifresi { get; set; }
        public string IsyeriSifresi { get; set; }
        public string BasvuruFormu { get; set; }
        public string Aphb { get; set; }
        public string BasvuruListesi7166 { get; set; }
        public string IsverenAdSoyad { get; set; }
        public string IsverenUnvan { get; set; }
        public string IsverenAdres { get; set; }
        public string IsverenSemt { get; set; }
        public string IsverenIlce { get; set; }
        public string IsverenIl { get; set; }
        public string IsverenDisKapiNo { get; set; }
        public string IsverenIcKapiNo { get; set; }
        public string IsverenPostaKodu { get; set; }
        public string IsverenTelefon { get; set; }
        public string IsverenEposta { get; set; }
        public string AltIsverenAdSoyad { get; set; }
        public string AltIsverenUnvan { get; set; }
        public string AltIsverenTcKimlikNo { get; set; }
        public string AltIsverenAdres { get; set; }
        public string AltIsverenSemt { get; set; }
        public string AltIsverenIlce { get; set; }
        public string AltIsverenIl { get; set; }
        public string AltIsverenDisKapiNo { get; set; }
        public string AltIsverenIcKapiNo { get; set; }
        public string AltIsverenPostaKodu { get; set; }
        public string AltIsverenTelefon { get; set; }
        public string AltIsverenEposta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsgariUcretDestekTutarlari> AsgariUcretDestekTutarlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruDonemleri> BasvuruDonemleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorcluAylar> BorcluAylar { get; set; }
        public virtual Sirketler Sirketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AylikCalisanSayilari> AylikCalisanSayilari { get; set; }
    }
}
