//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesvikProgrami
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sirketler> Sirketler { get; set; }
        public virtual DbSet<AsgariUcretDestekTutarlari> AsgariUcretDestekTutarlari { get; set; }
        public virtual DbSet<BasvuruDonemleri> BasvuruDonemleri { get; set; }
        public virtual DbSet<BelgeTurleri> BelgeTurleri { get; set; }
        public virtual DbSet<BorcluAylar> BorcluAylar { get; set; }
        public virtual DbSet<AsgariUcretler> AsgariUcretler { get; set; }
        public virtual DbSet<Isyerleri> Isyerleri { get; set; }
        public virtual DbSet<Ayarlar> Ayarlar { get; set; }
        public virtual DbSet<DonusturulecekKanunlar> DonusturulecekKanunlar { get; set; }
        public virtual DbSet<KisaVadeliSigortaPrimKoluOranlari> KisaVadeliSigortaPrimKoluOranlari { get; set; }
        public virtual DbSet<AylikCalisanSayilari> AylikCalisanSayilari { get; set; }
        public virtual DbSet<Cari14857YapilanSirketler> Cari14857YapilanSirketler { get; set; }
    }
}
